name: django-iam
version: 0.1.0-dev6
description: Roles and access management for django apps

repo_url: https://github.com/kaoslabsinc/django-iam
project_url: https://github.com/kaoslabsinc/django-iam
keywords: django, iam, users, auth, authorization, kaos
