name: django-iam
version: 0.2.0-rc3
description: Roles and access management for django apps

repo_url: https://github.com/kaoslabsinc/django-iam
project_url: https://github.com/kaoslabsinc/django-iam
keywords: django, iam, users, auth, authorization, kaos
