name: django-iam
version: 0.3.0-a6
description: Roles and access management for django apps

repo_url: https://github.com/kaoslabsinc/django-iam
project_url: https://github.com/kaoslabsinc/django-iam
keywords: django, iam, users, auth, authorization, kaos
