# Generated by Django 3.2.9 on 2022-01-25 03:42

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleadminprofile',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(100, 'Active'), (-1, 'Archived')], default=100),
        ),
    ]
