# Generated by Django 3.2.6 on 2021-08-17 16:17

from django.db import migrations, models
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
