# Generated by Django 3.2.6 on 2021-08-17 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_simplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('simple.simplemodel',),
        ),
    ]
