# Generated by Django 4.1.1 on 2022-09-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='is_super_author',
            field=models.BooleanField(default=False),
        ),
    ]
