# Generated by Django 3.2.6 on 2021-08-17 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simple', '0003_simpleproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplemanager',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simplemanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='simple_manager_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
