# Generated by Django 3.2.6 on 2021-08-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0003_simpleproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplemanager',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
