# Generated by Django 3.2.9 on 2022-01-29 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_status', django_fsm.FSMIntegerField(choices=[(100, 'Active'), (-1, 'Archived')], default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='app_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'app admin profiles 👤',
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
