# Generated by Django 3.2.9 on 2021-11-08 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='blog_author_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'blog author profiles 👤',
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
