# Generated by Django 3.2.9 on 2021-11-04 19:09

from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogauthorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to='blog.blogauthorprofile')),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
