# Generated by Django 3.2.9 on 2022-01-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthorprofile',
            name='is_privileged',
            field=models.BooleanField(default=False),
        ),
    ]
